export type UsersMockedData = {
	id: number;
	firstName: string;
	lastName: string;
	salary: number;
	department: string;
	jobTitle: string;
};

export const usersMocked: UsersMockedData[] = [
	{
		id: 1,
		firstName: 'Sukey',
		lastName: 'Mynott',
		salary: 1000,
		department: 'Sales',
		jobTitle: 'afsdafsdfasdfasidjfsidafosafsadnfjsfdlfjladf sdfisdaljkfnflsdflasfjksdakjfsak Civil Engineer',
	},
	{
		id: 2,
		firstName: 'Angeline',
		lastName: 'Arlett',
		salary: 1000,
		department: 'Human Resources',
		jobTitle: 'afsdafsdfasdfasidjfsidafosafsadnfjsfdlfjladf sdfisdaljkfnflsdflasfjksdakjfsak Accounting Assistant II',
	},
	{
		id: 3,
		firstName: 'Palmer',
		lastName: 'McIlwraith',
		salary: 1000,
		department: 'Product Management',
		jobTitle: 'Systems Administrator IV',
	},
	{
		id: 4,
		firstName: 'Nancie',
		lastName: 'Alldread',
		salary: 1000,
		department: 'Sales',
		jobTitle: 'Safety Technician IV',
	},
	{
		id: 5,
		firstName: 'Hinze',
		lastName: 'Larimer',
		salary: 1000,
		department: 'Marketing',
		jobTitle: 'Health Coach II',
	},
	{
		id: 6,
		firstName: 'Robert',
		lastName: 'MacDonough',
		salary: 1000,
		department: 'Business Development',
		jobTitle: 'Office Assistant II',
	},
	{
		id: 7,
		firstName: 'Jennilee',
		lastName: 'Bachelor',
		salary: 1000,
		department: 'Services',
		jobTitle: 'Recruiting Manager',
	},
	{
		id: 8,
		firstName: 'Sayer',
		lastName: 'Moralis',
		salary: 1000,
		department: 'Research and Development',
		jobTitle: 'Electrical Engineer',
	},
	{
		id: 9,
		firstName: 'Wilhelm',
		lastName: 'De Gowe',
		salary: 1000,
		department: 'Services',
		jobTitle: 'Sales Representative',
	},
	{
		id: 10,
		firstName: 'Kiley',
		lastName: 'Alder',
		salary: 1000,
		department: 'Product Management',
		jobTitle: 'Analyst Programmer',
	},
	{
		id: 11,
		firstName: 'Judon',
		lastName: 'Heck',
		salary: 1000,
		department: 'Services',
		jobTitle: 'Director of Sales',
	},
	{
		id: 12,
		firstName: 'Darline',
		lastName: 'Koopman',
		salary: 1000,
		department: 'Training',
		jobTitle: 'Administrative Officer',
	},
	{
		id: 13,
		firstName: 'Bowie',
		lastName: 'Burnell',
		salary: 1000,
		department: 'Human Resources',
		jobTitle: 'Web Developer I',
	},
	{
		id: 14,
		firstName: 'Joseph',
		lastName: 'Bulluck',
		salary: 1000,
		department: 'Business Development',
		jobTitle: 'Recruiting Manager',
	},
	{
		id: 15,
		firstName: 'Geralda',
		lastName: 'Minett',
		salary: 1000,
		department: 'Sales',
		jobTitle: 'GIS Technical Architect',
	},
	{
		id: 16,
		firstName: 'Ginnifer',
		lastName: 'Bugler',
		salary: 1000,
		department: 'Engineering',
		jobTitle: 'Research Associate',
	},
	{
		id: 17,
		firstName: 'Yorker',
		lastName: 'Cree',
		salary: 1000,
		department: 'Human Resources',
		jobTitle: 'Senior Sales Associate',
	},
	{
		id: 18,
		firstName: 'Lianne',
		lastName: 'Fullager',
		salary: 1000,
		department: 'Sales',
		jobTitle: 'Assistant Manager',
	},
	{
		id: 19,
		firstName: 'Carmine',
		lastName: 'Wagstaffe',
		salary: 1000,
		department: 'Legal',
		jobTitle: 'Biostatistician III',
	},
	{
		id: 20,
		firstName: 'Worth',
		lastName: 'Aitkin',
		salary: 1000,
		department: 'Services',
		jobTitle: 'Design Engineer',
	},
	{
		id: 21,
		firstName: 'Reba',
		lastName: 'Kingaby',
		salary: 1000,
		department: 'Engineering',
		jobTitle: 'VP Marketing',
	},
	{
		id: 22,
		firstName: 'Kincaid',
		lastName: 'Spinney',
		salary: 1000,
		department: 'Engineering',
		jobTitle: 'Quality Engineer',
	},
	{
		id: 23,
		firstName: 'Luther',
		lastName: 'Threadgold',
		salary: 1000,
		department: 'Research and Development',
		jobTitle: 'General Manager',
	},
	{
		id: 24,
		firstName: 'Tanitansy',
		lastName: 'Romanin',
		salary: 1000,
		department: 'Sales',
		jobTitle: 'Administrative Officer',
	},
	{
		id: 25,
		firstName: 'Ethel',
		lastName: 'Cabral',
		salary: 1000,
		department: 'Marketing',
		jobTitle: 'Assistant Media Planner',
	},
	{
		id: 26,
		firstName: 'Olly',
		lastName: 'Ishchenko',
		salary: 1000,
		department: 'Human Resources',
		jobTitle: 'Research Assistant IV',
	},
	{
		id: 27,
		firstName: 'Ilse',
		lastName: 'Geldert',
		salary: 1000,
		department: 'Training',
		jobTitle: 'Electrical Engineer',
	},
	{
		id: 28,
		firstName: 'Belle',
		lastName: 'McJerrow',
		salary: 1000,
		department: 'Sales',
		jobTitle: 'Physical Therapy Assistant',
	},
	{
		id: 29,
		firstName: 'Antonietta',
		lastName: 'Mathevon',
		salary: 1000,
		department: 'Sales',
		jobTitle: 'Recruiter',
	},
	{
		id: 30,
		firstName: 'De witt',
		lastName: 'Houltham',
		salary: 1000,
		department: 'Accounting',
		jobTitle: 'Administrative Officer',
	},
	{
		id: 31,
		firstName: 'Courtnay',
		lastName: 'Shaudfurth',
		salary: 1000,
		department: 'Business Development',
		jobTitle: 'Legal Assistant',
	},
	{
		id: 32,
		firstName: 'Conney',
		lastName: 'Boog',
		salary: 1000,
		department: 'Product Management',
		jobTitle: 'Research Assistant III',
	},
	{
		id: 33,
		firstName: 'Selma',
		lastName: 'Lambourn',
		salary: 1000,
		department: 'Sales',
		jobTitle: 'Account Executive',
	},
	{
		id: 34,
		firstName: 'Shaun',
		lastName: 'Cassley',
		salary: 1000,
		department: 'Human Resources',
		jobTitle: 'Database Administrator IV',
	},
	{
		id: 35,
		firstName: 'Rolando',
		lastName: 'Donaghy',
		salary: 1000,
		department: 'Services',
		jobTitle: 'Web Designer IV',
	},
	{
		id: 36,
		firstName: 'Elora',
		lastName: 'Heald',
		salary: 1000,
		department: 'Legal',
		jobTitle: 'Compensation Analyst',
	},
	{
		id: 37,
		firstName: 'Sammy',
		lastName: 'Peddersen',
		salary: 1000,
		department: 'Product Management',
		jobTitle: 'Operator',
	},
	{
		id: 38,
		firstName: 'Janine',
		lastName: 'Habbal',
		salary: 1000,
		department: 'Business Development',
		jobTitle: 'Cost Accountant',
	},
	{
		id: 39,
		firstName: 'Kaela',
		lastName: 'Quogan',
		salary: 1000,
		department: 'Research and Development',
		jobTitle: 'General Manager',
	},
	{
		id: 40,
		firstName: 'Karole',
		lastName: 'Stronge',
		salary: 1000,
		department: 'Human Resources',
		jobTitle: 'Software Engineer IV',
	},
	{
		id: 41,
		firstName: 'Essy',
		lastName: 'Oxshott',
		salary: 1000,
		department: 'Research and Development',
		jobTitle: 'Civil Engineer',
	},
	{
		id: 42,
		firstName: 'Darya',
		lastName: 'Macer',
		salary: 1000,
		department: 'Training',
		jobTitle: 'Social Worker',
	},
	{
		id: 43,
		firstName: 'Ira',
		lastName: 'Pittel',
		salary: 1000,
		department: 'Marketing',
		jobTitle: 'Office Assistant IV',
	},
	{
		id: 44,
		firstName: 'Sabine',
		lastName: 'Burgiss',
		salary: 1000,
		department: 'Sales',
		jobTitle: 'Assistant Media Planner',
	},
	{
		id: 45,
		firstName: 'Arleyne',
		lastName: 'Colvin',
		salary: 1000,
		department: 'Research and Development',
		jobTitle: 'Account Representative I',
	},
	{
		id: 46,
		firstName: 'Giff',
		lastName: 'McCafferky',
		salary: 1000,
		department: 'Legal',
		jobTitle: 'Software Engineer IV',
	},
	{
		id: 47,
		firstName: 'Calypso',
		lastName: 'Wordsley',
		salary: 1000,
		department: 'Research and Development',
		jobTitle: 'Account Representative II',
	},
	{
		id: 48,
		firstName: 'Freda',
		lastName: 'Lines',
		salary: 1000,
		department: 'Support',
		jobTitle: 'Accounting Assistant I',
	},
	{
		id: 49,
		firstName: 'Glenna',
		lastName: 'Buncher',
		salary: 1000,
		department: 'Product Management',
		jobTitle: 'Quality Control Specialist',
	},
	{
		id: 50,
		firstName: 'Reuben',
		lastName: 'Tregensoe',
		salary: 1000,
		department: 'Research and Development',
		jobTitle: 'Payment Adjustment Coordinator',
	},
	{
		id: 51,
		firstName: 'Dania',
		lastName: 'Earthfield',
		salary: 1000,
		department: 'Sales',
		jobTitle: 'Business Systems Development Analyst',
	},
	{
		id: 52,
		firstName: 'Audie',
		lastName: 'Morl',
		salary: 1000,
		department: 'Sales',
		jobTitle: 'Media Manager III',
	},
	{
		id: 53,
		firstName: 'Darwin',
		lastName: 'Gutans',
		salary: 1000,
		department: 'Research and Development',
		jobTitle: 'VP Marketing',
	},
	{
		id: 54,
		firstName: 'Korney',
		lastName: "I'anson",
		salary: 1000,
		department: 'Engineering',
		jobTitle: 'Compensation Analyst',
	},
	{
		id: 55,
		firstName: 'Lorelle',
		lastName: 'Lehrer',
		salary: 1000,
		department: 'Sales',
		jobTitle: 'Mechanical Systems Engineer',
	},
	{
		id: 56,
		firstName: 'Ellis',
		lastName: 'Privost',
		salary: 1000,
		department: 'Product Management',
		jobTitle: 'Senior Quality Engineer',
	},
	{
		id: 57,
		firstName: 'Annabela',
		lastName: 'Nower',
		salary: 1000,
		department: 'Engineering',
		jobTitle: 'Speech Pathologist',
	},
	{
		id: 58,
		firstName: 'Donnell',
		lastName: 'Oldland',
		salary: 1000,
		department: 'Training',
		jobTitle: 'Civil Engineer',
	},
	{
		id: 59,
		firstName: 'Cassondra',
		lastName: 'Knowller',
		salary: 1000,
		department: 'Marketing',
		jobTitle: 'Librarian',
	},
	{
		id: 60,
		firstName: 'Bear',
		lastName: 'Dilloway',
		salary: 1000,
		department: 'Engineering',
		jobTitle: 'Help Desk Technician',
	},
	{
		id: 61,
		firstName: 'Lamond',
		lastName: 'Skentelbery',
		salary: 1000,
		department: 'Product Management',
		jobTitle: 'Recruiter',
	},
	{
		id: 62,
		firstName: 'Janna',
		lastName: 'Coultass',
		salary: 1000,
		department: 'Sales',
		jobTitle: 'Automation Specialist IV',
	},
	{
		id: 63,
		firstName: 'Dennison',
		lastName: 'Bissatt',
		salary: 1000,
		department: 'Product Management',
		jobTitle: 'Geological Engineer',
	},
	{
		id: 64,
		firstName: 'Betty',
		lastName: 'Victor',
		salary: 1000,
		department: 'Services',
		jobTitle: 'Chemical Engineer',
	},
	{
		id: 65,
		firstName: 'Reidar',
		lastName: 'Tanfield',
		salary: 1000,
		department: 'Sales',
		jobTitle: 'VP Sales',
	},
	{
		id: 66,
		firstName: 'Angelia',
		lastName: 'Smoughton',
		salary: 1000,
		department: 'Business Development',
		jobTitle: 'Design Engineer',
	},
	{
		id: 67,
		firstName: 'Korella',
		lastName: 'Corran',
		salary: 1000,
		department: 'Legal',
		jobTitle: 'Computer Systems Analyst II',
	},
	{
		id: 68,
		firstName: 'Berrie',
		lastName: 'Robottom',
		salary: 1000,
		department: 'Product Management',
		jobTitle: 'Civil Engineer',
	},
	{
		id: 69,
		firstName: 'Giana',
		lastName: 'Madgett',
		salary: 1000,
		department: 'Accounting',
		jobTitle: 'Programmer Analyst II',
	},
	{
		id: 70,
		firstName: 'Dari',
		lastName: 'Stothart',
		salary: 1000,
		department: 'Human Resources',
		jobTitle: 'Speech Pathologist',
	},
	{
		id: 71,
		firstName: 'Taddeo',
		lastName: 'Giacomelli',
		salary: 1000,
		department: 'Research and Development',
		jobTitle: 'Human Resources Manager',
	},
	{
		id: 72,
		firstName: 'Robbie',
		lastName: 'Mullineux',
		salary: 1000,
		department: 'Legal',
		jobTitle: 'Legal Assistant',
	},
	{
		id: 73,
		firstName: 'Tomi',
		lastName: 'Grzelak',
		salary: 1000,
		department: 'Engineering',
		jobTitle: 'Web Developer IV',
	},
	{
		id: 74,
		firstName: 'Bidget',
		lastName: 'Doorbar',
		salary: 1000,
		department: 'Services',
		jobTitle: 'Office Assistant I',
	},
	{
		id: 75,
		firstName: 'Melinda',
		lastName: 'Glaze',
		salary: 1000,
		department: 'Training',
		jobTitle: 'Clinical Specialist',
	},
	{
		id: 76,
		firstName: 'Georgi',
		lastName: 'Ottewell',
		salary: 1000,
		department: 'Accounting',
		jobTitle: 'Help Desk Technician',
	},
	{
		id: 77,
		firstName: 'Jonis',
		lastName: 'Indgs',
		salary: 1000,
		department: 'Product Management',
		jobTitle: 'Pharmacist',
	},
	{
		id: 78,
		firstName: 'Brewster',
		lastName: 'Quaif',
		salary: 1000,
		department: 'Training',
		jobTitle: 'Desktop Support Technician',
	},
	{
		id: 79,
		firstName: 'Patience',
		lastName: 'Hymers',
		salary: 1000,
		department: 'Support',
		jobTitle: 'Account Executive',
	},
	{
		id: 80,
		firstName: 'Alessandra',
		lastName: 'Rankcom',
		salary: 1000,
		department: 'Legal',
		jobTitle: 'Analyst Programmer',
	},
	{
		id: 81,
		firstName: 'Dewey',
		lastName: 'Astridge',
		salary: 1000,
		department: 'Legal',
		jobTitle: 'Accounting Assistant II',
	},
	{
		id: 82,
		firstName: 'Andrea',
		lastName: 'Fasey',
		salary: 1000,
		department: 'Accounting',
		jobTitle: 'Structural Analysis Engineer',
	},
	{
		id: 83,
		firstName: 'Culver',
		lastName: 'Ratnage',
		salary: 1000,
		department: 'Human Resources',
		jobTitle: 'Compensation Analyst',
	},
	{
		id: 84,
		firstName: 'Marketa',
		lastName: 'Surgood',
		salary: 1000,
		department: 'Accounting',
		jobTitle: 'Automation Specialist III',
	},
	{
		id: 85,
		firstName: 'Loren',
		lastName: 'Hymas',
		salary: 1000,
		department: 'Product Management',
		jobTitle: 'Media Manager III',
	},
	{
		id: 86,
		firstName: 'Gerrard',
		lastName: 'Villa',
		salary: 1000,
		department: 'Human Resources',
		jobTitle: 'Mechanical Systems Engineer',
	},
	{
		id: 87,
		firstName: 'Andre',
		lastName: 'Rotge',
		salary: 1000,
		department: 'Legal',
		jobTitle: 'Product Engineer',
	},
	{
		id: 88,
		firstName: 'Geoffrey',
		lastName: 'Iddy',
		salary: 1000,
		department: 'Research and Development',
		jobTitle: 'Tax Accountant',
	},
	{
		id: 89,
		firstName: 'Hilary',
		lastName: 'Grinaway',
		salary: 1000,
		department: 'Human Resources',
		jobTitle: 'Automation Specialist IV',
	},
	{
		id: 90,
		firstName: 'Myrtie',
		lastName: 'Cantua',
		salary: 1000,
		department: 'Engineering',
		jobTitle: 'Clinical Specialist',
	},
	{
		id: 91,
		firstName: 'Aileen',
		lastName: 'Pulford',
		salary: 1000,
		department: 'Human Resources',
		jobTitle: 'VP Accounting',
	},
	{
		id: 92,
		firstName: 'Tonie',
		lastName: 'Bellamy',
		salary: 1000,
		department: 'Services',
		jobTitle: 'Developer IV',
	},
	{
		id: 93,
		firstName: 'Tonya',
		lastName: 'Conelly',
		salary: 1000,
		department: 'Legal',
		jobTitle: 'Product Engineer',
	},
	{
		id: 94,
		firstName: 'Goddart',
		lastName: 'Illes',
		salary: 1000,
		department: 'Sales',
		jobTitle: 'Analyst Programmer',
	},
	{
		id: 95,
		firstName: 'Grannie',
		lastName: 'Rowen',
		salary: 1000,
		department: 'Human Resources',
		jobTitle: 'Speech Pathologist',
	},
	{
		id: 96,
		firstName: 'Lita',
		lastName: 'Jolliff',
		salary: 1000,
		department: 'Business Development',
		jobTitle: 'Administrative Assistant I',
	},
	{
		id: 97,
		firstName: 'Esme',
		lastName: 'Hanby',
		salary: 1000,
		department: 'Legal',
		jobTitle: 'Project Manager',
	},
	{
		id: 100,
		firstName: 'Gale',
		lastName: 'Momford',
		salary: 1000,
		department: 'Engineering',
		jobTitle: 'Account Representative II',
	},
];
